---
title: "R Notebook"
output: html_notebook
---



```{r}
# load libraries and source
library(dplyr)
library(tidyr)
library(data.table)
library(devtools)
```

```{r}
# load csv file

t_personas <- read.table("data/DATA_USER_EXPERIMENT/data_processed/participants_personas_processed.csv", TRUE, ",")

head(t_personas)

```




```{r}


data = dplyr::select(t_personas, starts_with("PS"))
    fit <- princomp(data, cor=FALSE, )
    fit$loadings[,3]
    
```

```{r}
names(fit)
    
```

```{r}
fit$loadings

```



```{r}
 summary(fit)
```

```{r}
fit
```



```{r}
t_personas$companionship = -as.matrix(data) %*% fit$loadings[,1]
t_personas$investment = as.matrix(data) %*% fit$loadings[,2]
t_personas$usage_of_mrs = -as.matrix(data) %*% fit$loadings[,3]
```

```{r}
head(t_personas)
```



```{r}
t_personas$companionship


```


```{r}
t_personas = dplyr::select(t_personas, -starts_with("persona"))
    t_personas$usage_of_mrs <- NULL
```

```{r}
head(t_personas)
```

```{r}
library("factoextra")
```


```{r}
fviz_eig(fit) # Visualization of variance explained by each component
```

```{r}
# Variable plot
fviz_pca_var(fit,
             col.var = "contrib", # Control variable color using their contributions to the PC
             gradient.cols = c("#70f6ff", "#00AFBB", "#ffd224",
                               "#d8ac00", "#FC4E07", "#a73203"),
             repel = TRUE,     # Avoid text overlapping
             ggtheme = theme_minimal()
             )
```

```{r}
# Biplot
fviz_pca_biplot(fit, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
                )
```

```{r}
# Compute the coordinate of variables
func_varcoord <- function(loading, comp.std){
  loading * comp.std} # First create a function computing the multiplication of loading and component standard deviation
loading <- fit$loading
std <- fit$sdev
varcoord <- t(apply(loading, 1, func_varcoord, std))
varcoord[,1:2] # Compute only PC1 and PC2
```

```{r}
t_personas

```


# save in csv

```{r}
write.csv(t_personas, file = "data/DATA_USER_EXPERIMENT/data_processed/participants_personas_processed_after_PCA.csv", row.names=FALSE)
```

